### ISSUE TITLE
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0

### ISSUE THREAD

**Issue by zNiinZe** [metaplex-foundation/metaplex#1153]
**hi so iv run into a problem with  create_candy_machine part not sure exactly what the problem is, Thought it would be that i dont have enough SOL but i dont think thats it, any help would be much appreciated.  **

> ts-node js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair 
> ~/.config/solana/devnet-test.json --price 1 
> wallet public key: ***************************
> Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
>     Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
>     Program 11111111111111111111111111111111 invoke [2]
>     Allocate: account Address { address: 55BAxy4LGH1UYZR6PJNzuTMmgnok4UvcUXLQG6ydkoaG, base: None } already in use
>     Program 11111111111111111111111111111111 failed: custom program error: 0x0
>     Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
>     Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: custom program error: 0x0
> Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom 
> program error: 0x0

**Comment by Fulgurus** [comment]
I fixed that issue by deleting metaplex .cache folder.

 and renaming my assets into 0.json 0.png (which were previously named test.json test.png).

And re-executing this command :
> ts-node ./js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair [path]/devnet.json

Then the create_candy_machine command (with custom spl-token) passed with success:

> ts-node ./js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair [path]/devnet.json --spl-token <TOKEN> --spl-token-account <ACCOUNT>

Hope it will fix your issue.

Andrew - The Gatsby Club

**Comment by zNiinZe** [comment]
> I fixed that issue by deleting metaplex .cache folder.
> 
> and renaming my assets into 0.json 0.png (which were previously named test.json test.png).
> 
> And re-executing this command :
> 
> > ts-node ./js/packages/cli/src/candy-machine-cli.ts upload ./assets --env devnet --keypair [path]/devnet.json
> 
> Then the create_candy_machine command (with custom spl-token) passed with success:
> 
> > ts-node ./js/packages/cli/src/candy-machine-cli.ts create_candy_machine --env devnet --keypair [path]/devnet.json --spl-token  --spl-token-account
> 
> Hope it will fix your issue.
> 
> Andrew - The Gatsby Club

Thx so much it helped ...(*￣０￣)ノ

**Comment by ankitdsgn** [comment]
> 

I am still getting the same error
plz help :)

**Comment by CarlSpobble** [comment]
Me too! I deleted the .cache folder..rerun the ts node upload command and still getting the same error..

**Comment by Fulgurus** [comment]
Commands have been updated with the recent candy machine V2 upgrade.
Have a look in their documentation for proper commands : https://docs.metaplex.com/candy-machine-v2/creating-candy-machine
