### ISSUE TITLE
[Bug]:  Error: failed to get recent blockhash

### ISSUE THREAD

**Issue by GottliebGlob** [metaplex-foundation/metaplex#1989]
### Which package is this bug report for?

candy machine cli

### Issue description

When I try to upload to mainnet via arweave-sol this error happen every time. 
![image](https://user-images.githubusercontent.com/53971863/159232931-ae3178c9-b36c-4b72-855e-2cae49e07348.png)

### Command

```shell
npx ts-node C:/Users/glebg/Data/Projects/candy-lab/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e mainnet-beta -k Se4Gf2GsjgzZZyUfnhFVzVLcijsCXx5a9Erhsp5uoUF.json -cp config.json assets
```

### Relevant log output

```shell
initialized config for a candy machine with publickey: 3VeDdKgq5grmtCZD5jP8tCzWZXdd3gh6icbvFBV5hfYA
[0] out of [10] items have been uploaded
Starting upload for [10] items, format {"mediaExt":".png","index":"0"}
Saved bundle upload result to cache.
Computed Bundle range, including 10 file pair(s) totaling 0.047MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 10/10
Uploading bundle via Bundlr... in multiple transactions
0.000078441 SOL to upload 0.343MB with buffer. Sending fund txn...
upload was not successful, please re-run. Error: failed to get recent blockhash: FetchError: request to https://api.metaplex.rpcpool.com/ failed, reason: g
etaddrinfo ENOTFOUND api.metaplex.rpcpool.com
    at Connection.getRecentBlockhash (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:3130:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SolanaConfig.getFee (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\node_modules\@bundlr-network\client\build\node\currencies\solana.js:91
:23)
    at async Fund.fund (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\node_modules\@bundlr-network\client\build\common\fund.js:26:25)
    at async processBundle (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\packages\cli\src\helpers\upload\arweave-bundle.ts:621:9)
    at async uploadV2 (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\packages\cli\src\commands\upload.ts:247:11)
    at async Command.<anonymous> (C:\Users\glebg\Data\Projects\candy-lab\metaplex\js\packages\cli\src\candy-machine-v2-cli.ts:269:7)
```

### Operating system

win10

### Priority this issue should have

High (immediate attention needed)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by ddcc3388** [comment]
Had the same issue

**Comment by stegaBOB** [comment]
Should be fixed by #1995. Let us know if its still an issue once that fix is merged in.

**Comment by GottliebGlob** [comment]
> Should be fixed by #1995. Let us know if its still an issue once that fix is merged in.

Fixed, thanks

**Comment by gbrads** [comment]
@GottliebGlob what did you do to fix this issue, i have the same and just paid the rent cost for the candy machine..

**Comment by pedroilin24** [comment]
im having the same issue

**Comment by pedroilin24** [comment]
> Should be fixed by #1995. Let us know if its still an issue once that fix is merged in.

hi, i should change the RPC and thats it???

**Comment by SkippCode** [comment]
I still have that same issue. I am unsure of what to do. I change the RPC as well. and it is a no go. I have animation NFTs. (image+animation+json)

**Comment by Jalapina** [comment]
Having the same issue on devnet
